# Generated by Django 5.0.6 on 2024-06-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuredProperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperty',
            name='price',
            field=models.IntegerField(),
        ),
    ]
