# Generated by Django 5.0.6 on 2024-06-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuredProperty', '0003_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproperty',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
