# Generated by Django 5.0.6 on 2024-06-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuredProperty', '0004_featuredproperty_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='featured_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='featuredProperty.featuredproperty'),
        ),
    ]
