# Generated by Django 5.0.6 on 2024-06-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aawasUser', '0004_alter_user_email'),
        ('featuredProperty', '0006_featuredproperty_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperty',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aawasUser.user'),
        ),
    ]
