# Generated by Django 5.0.6 on 2024-06-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=23)),
                ('phoneNumber', models.CharField(max_length=14, unique=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gender', to='aawasUser.gender')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membership', to='aawasUser.membership')),
            ],
        ),
    ]
