# Generated by Django 5.0.6 on 2024-06-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aawasUser', '0002_alter_user_email_alter_user_password_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=23),
        ),
        migrations.DeleteModel(
            name='UserImg',
        ),
    ]
